name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/sourcemanager
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@postgres:5432/sourcemanager

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Start chromedriver and Xvfb
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Wait for Postgres
        run: |
          until pg_isready -h postgres -p 5432 -U postgres; do
            echo "Waiting for Postgres..."
            sleep 2
          done
      - name: Run Robot tests
        run: bash run_robot_tests.sh
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
